a=0
t=0
g=0
c=0
dna="AAGACCCCCTGATTCCCACGATTGAGTACGGATTTGCTACAGCTGTCCGATATGCCACCATCCCTTCTAGTGGAGGCGATAGCGTCCAAGGGTGCTTTGAGGACTTGTACCCCAGATTGGCAGTCGTAGCAACTCACCATGTCACAGTGCCGGGATCGATGTGTTCTGCTCTGTCGTAAGCCCTGTTAAAGTATATATTTAAAGATCACTCCCCAGTAACCGCACGTTAGCCCCAAGTCAATATATGACTCCGCCGGTGATGTATTATGAATACTTAGAAGCCTTCAGCCGAAGCGCCTGGGAGCAGCCTGGAACTTTGATGCGGAGAAAACATTAGAGAGATCTGGATAATCAAATTGGCGAGTCAACTACATTGAGTCGGACAGATGCTGAGCACTCCATCAGAAATGCCTTGGCTGAAACAGTGAGGGGTCTAGGTCTGCATTAAAGAGCCAGTCGTCGCACTGCCCGTTTCCTACCTACTCGTGTTTGGCGATAACGTTGTACGTATCGATCGCAAGGACATCTCATCTCCGGATTATTGTGCAAAGTCATGCATTTTATAGATAAAGGGAGCGTATGGGGCACTTATTCCTTGATGAGTATGAGCGCTGCACTCGCCCCGTATGACGTCTACGGTTATTTCTGGGCGCCCACAATTGGGTTCAGAGGCACCGCAACCATAGTAAATCTATCTTGACTACGTCTTTTCTGTGCAGGGCGGCCCTATTCGCTCACGCTCAACGATAGCCGGGGACGCAACCGAACTTGGACCCAAAGTAGAGGCTAGGCAGGGTTTGTGCTGCTAGTCATTTTTATTGCACCCCATCGTATTATATCAGAATATCCGAAATAGAACAGTATATAGCGAGGAGACTCATCAGGATCTCTCCCCAGG"
for s in dna:
    if s =="A":
        a = a+1
    elif s == "T":
        t = t+1
    elif s == "G":
        g = g+1
    else:
        c = c+1
print (a,c,g,t)







